//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autossential.Workbook.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Autossential.Workbook.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autossential.Workbook.
        /// </summary>
        public static string ActivityCategories_Workbook {
            get {
                return ResourceManager.GetString("ActivityCategories_Workbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autossential.Workbook.Cell.
        /// </summary>
        public static string ActivityCategories_Workbook_Cell {
            get {
                return ResourceManager.GetString("ActivityCategories_Workbook_Cell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autossential.Workbook.Range.
        /// </summary>
        public static string ActivityCategories_Workbook_Range {
            get {
                return ResourceManager.GetString("ActivityCategories_Workbook_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autossential.Workbook.Sheet.
        /// </summary>
        public static string ActivityCategories_Workbook_Sheet {
            get {
                return ResourceManager.GetString("ActivityCategories_Workbook_Sheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Categories_Input {
            get {
                return ResourceManager.GetString("Categories_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input/Output.
        /// </summary>
        public static string Categories_InputOutput {
            get {
                return ResourceManager.GetString("Categories_InputOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Categories_Options {
            get {
                return ResourceManager.GetString("Categories_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Categories_Output {
            get {
                return ResourceManager.GetString("Categories_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies to continue executing the remaining activities even if the current activity failed. Only boolean values are allowed..
        /// </summary>
        public static string Common_ContinueOnError_Description {
            get {
                return ResourceManager.GetString("Common_ContinueOnError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue on error.
        /// </summary>
        public static string Common_ContinueOnError_DisplayName {
            get {
                return ResourceManager.GetString("Common_ContinueOnError_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value for a required activity argument &apos;{0}&apos; was not supplied..
        /// </summary>
        public static string Common_ErrorMsg_ValueNotSupplied {
            get {
                return ResourceManager.GetString("Common_ErrorMsg_ValueNotSupplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the amount of time in seconds to wait for the activity to run before an error is thrown. The default value is 30s..
        /// </summary>
        public static string Common_TimeoutSeconds_Description {
            get {
                return ResourceManager.GetString("Common_TimeoutSeconds_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        public static string Common_TimeoutSeconds_DisplayName {
            get {
                return ResourceManager.GetString("Common_TimeoutSeconds_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be used outside of {0} activity..
        /// </summary>
        public static string Common_UsingOutsideOfScope {
            get {
                return ResourceManager.GetString("Common_UsingOutsideOfScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for file.
        /// </summary>
        public static string Common_ViewModel_BrowseForFile {
            get {
                return ResourceManager.GetString("Common_ViewModel_BrowseForFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for folder.
        /// </summary>
        public static string Common_ViewModel_BrowseForFolder {
            get {
                return ResourceManager.GetString("Common_ViewModel_BrowseForFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes a specified worksheet from the workbook. Use this activity when you need to remove unwanted sheets from the workbook..
        /// </summary>
        public static string DeleteSheet_Description {
            get {
                return ResourceManager.GetString("DeleteSheet_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Sheet.
        /// </summary>
        public static string DeleteSheet_DisplayName {
            get {
                return ResourceManager.GetString("DeleteSheet_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the worksheet to be deleted. This property is required and the sheet must exist in the workbook..
        /// </summary>
        public static string DeleteSheet_SheetName_Description {
            get {
                return ResourceManager.GetString("DeleteSheet_SheetName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet Name.
        /// </summary>
        public static string DeleteSheet_SheetName_DisplayName {
            get {
                return ResourceManager.GetString("DeleteSheet_SheetName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the address of the cell containing the value (e.g., &quot;B4&quot;)..
        /// </summary>
        public static string FindValue_CellAddress_Description {
            get {
                return ResourceManager.GetString("FindValue_CellAddress_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Address.
        /// </summary>
        public static string FindValue_CellAddress_DisplayName {
            get {
                return ResourceManager.GetString("FindValue_CellAddress_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the 1-based column number of the cell containing the value (e.g., 2 for cell B4)..
        /// </summary>
        public static string FindValue_ColumnNumber_Description {
            get {
                return ResourceManager.GetString("FindValue_ColumnNumber_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Number.
        /// </summary>
        public static string FindValue_ColumnNumber_DisplayName {
            get {
                return ResourceManager.GetString("FindValue_ColumnNumber_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searches for a specified value within an Excel worksheet range and returns the cell address, row number, and column number of the first occurrence. Use this activity when you need to locate specific data within a workbook and retrieve its coordinates for further processing..
        /// </summary>
        public static string FindValue_Description {
            get {
                return ResourceManager.GetString("FindValue_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Value.
        /// </summary>
        public static string FindValue_DisplayName {
            get {
                return ResourceManager.GetString("FindValue_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell range to search within (e.g., &quot;A1:C10&quot;). If not provided, defaults to &quot;A1&quot; which searches the entire worksheet..
        /// </summary>
        public static string FindValue_Range_Description {
            get {
                return ResourceManager.GetString("FindValue_Range_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        public static string FindValue_Range_DisplayName {
            get {
                return ResourceManager.GetString("FindValue_Range_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the 1-based row number of the cell containing the value (e.g., 4 for cell B4)..
        /// </summary>
        public static string FindValue_RowNumber_Description {
            get {
                return ResourceManager.GetString("FindValue_RowNumber_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row Number.
        /// </summary>
        public static string FindValue_RowNumber_DisplayName {
            get {
                return ResourceManager.GetString("FindValue_RowNumber_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the worksheet to search for the value. This property is required and the sheet must exist in the workbook..
        /// </summary>
        public static string FindValue_SheetName_Description {
            get {
                return ResourceManager.GetString("FindValue_SheetName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet Name.
        /// </summary>
        public static string FindValue_SheetName_DisplayName {
            get {
                return ResourceManager.GetString("FindValue_SheetName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specific text or numeric value to locate within the worksheet range. This property is required and performs an exact match search..
        /// </summary>
        public static string FindValue_Value_Description {
            get {
                return ResourceManager.GetString("FindValue_Value_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string FindValue_Value_DisplayName {
            get {
                return ResourceManager.GetString("FindValue_Value_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the number of columns to freeze from the left. If set to 0, no columns will be frozen..
        /// </summary>
        public static string FreezePanes_ColumnsToFreeze_Description {
            get {
                return ResourceManager.GetString("FreezePanes_ColumnsToFreeze_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns to Freeze.
        /// </summary>
        public static string FreezePanes_ColumnsToFreeze_DisplayName {
            get {
                return ResourceManager.GetString("FreezePanes_ColumnsToFreeze_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freezes specified rows and columns in a worksheet, keeping them visible while scrolling through the rest of the sheet..
        /// </summary>
        public static string FreezePanes_Description {
            get {
                return ResourceManager.GetString("FreezePanes_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze Panes.
        /// </summary>
        public static string FreezePanes_DisplayName {
            get {
                return ResourceManager.GetString("FreezePanes_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the number of rows to freeze from the top. If set to 0, no rows will be frozen..
        /// </summary>
        public static string FreezePanes_RowsToFreeze_Description {
            get {
                return ResourceManager.GetString("FreezePanes_RowsToFreeze_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows to Freeze.
        /// </summary>
        public static string FreezePanes_RowsToFreeze_DisplayName {
            get {
                return ResourceManager.GetString("FreezePanes_RowsToFreeze_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the worksheet where the panes will be frozen..
        /// </summary>
        public static string FreezePanes_SheetName_Description {
            get {
                return ResourceManager.GetString("FreezePanes_SheetName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet Name.
        /// </summary>
        public static string FreezePanes_SheetName_DisplayName {
            get {
                return ResourceManager.GetString("FreezePanes_SheetName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of columns in use included in the specified range..
        /// </summary>
        public static string GetRangeSize_ColumnCount_Description {
            get {
                return ResourceManager.GetString("GetRangeSize_ColumnCount_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Count.
        /// </summary>
        public static string GetRangeSize_ColumnCount_DisplayName {
            get {
                return ResourceManager.GetString("GetRangeSize_ColumnCount_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the bounding dimensions (rows and columns) of the specified range, trimming only trailing empty rows and columns..
        /// </summary>
        public static string GetRangeSize_Description {
            get {
                return ResourceManager.GetString("GetRangeSize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Range Size.
        /// </summary>
        public static string GetRangeSize_DisplayName {
            get {
                return ResourceManager.GetString("GetRangeSize_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the range of cells to be read. If this value is not specified, all used cells of the spreadsheet is read. If the value consists of only one cell, all used rows in the spreadsheet are read starting from that cell. (Default: A1).
        /// </summary>
        public static string GetRangeSize_Range_Description {
            get {
                return ResourceManager.GetString("GetRangeSize_Range_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        public static string GetRangeSize_Range_DisplayName {
            get {
                return ResourceManager.GetString("GetRangeSize_Range_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of rows in use included in the specified range..
        /// </summary>
        public static string GetRangeSize_RowCount_Description {
            get {
                return ResourceManager.GetString("GetRangeSize_RowCount_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row Count.
        /// </summary>
        public static string GetRangeSize_RowCount_DisplayName {
            get {
                return ResourceManager.GetString("GetRangeSize_RowCount_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the worksheet containing the target range..
        /// </summary>
        public static string GetRangeSize_SheetName_Description {
            get {
                return ResourceManager.GetString("GetRangeSize_SheetName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet Name.
        /// </summary>
        public static string GetRangeSize_SheetName_DisplayName {
            get {
                return ResourceManager.GetString("GetRangeSize_SheetName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the action to perform on the worksheet. Select Hide to make the sheet invisible, or Unhide to make it visible again..
        /// </summary>
        public static string HideUnhideSheet_Action_Description {
            get {
                return ResourceManager.GetString("HideUnhideSheet_Action_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string HideUnhideSheet_Action_DisplayName {
            get {
                return ResourceManager.GetString("HideUnhideSheet_Action_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hides or unhides a specified worksheet in the workbook..
        /// </summary>
        public static string HideUnhideSheet_Description {
            get {
                return ResourceManager.GetString("HideUnhideSheet_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide/Unhide Sheet.
        /// </summary>
        public static string HideUnhideSheet_DisplayName {
            get {
                return ResourceManager.GetString("HideUnhideSheet_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the worksheet to hide or unhide..
        /// </summary>
        public static string HideUnhideSheet_SheetName_Description {
            get {
                return ResourceManager.GetString("HideUnhideSheet_SheetName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet Name.
        /// </summary>
        public static string HideUnhideSheet_SheetName_DisplayName {
            get {
                return ResourceManager.GetString("HideUnhideSheet_SheetName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserts a new worksheet into the workbook with the specified name and optional position. Use this activity when you need to add a new sheet to the workbook..
        /// </summary>
        public static string InsertSheet_Description {
            get {
                return ResourceManager.GetString("InsertSheet_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Sheet.
        /// </summary>
        public static string InsertSheet_DisplayName {
            get {
                return ResourceManager.GetString("InsertSheet_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional index position where the new sheet will be inserted (1-based). If not provided or less than 1, the sheet is added at the end of the workbook..
        /// </summary>
        public static string InsertSheet_Position_Description {
            get {
                return ResourceManager.GetString("InsertSheet_Position_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string InsertSheet_Position_DisplayName {
            get {
                return ResourceManager.GetString("InsertSheet_Position_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the new worksheet to be inserted. This property is required and must be unique within the workbook..
        /// </summary>
        public static string InsertSheet_SheetName_Description {
            get {
                return ResourceManager.GetString("InsertSheet_SheetName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet Name.
        /// </summary>
        public static string InsertSheet_SheetName_DisplayName {
            get {
                return ResourceManager.GetString("InsertSheet_SheetName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cell address the value should be read from..
        /// </summary>
        public static string ReadCell_CellAddress_Description {
            get {
                return ResourceManager.GetString("ReadCell_CellAddress_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Address.
        /// </summary>
        public static string ReadCell_CellAddress_DisplayName {
            get {
                return ResourceManager.GetString("ReadCell_CellAddress_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reads a cell value in the specified sheet and cell address..
        /// </summary>
        public static string ReadCell_Description {
            get {
                return ResourceManager.GetString("ReadCell_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Cell.
        /// </summary>
        public static string ReadCell_DisplayName {
            get {
                return ResourceManager.GetString("ReadCell_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value read from the cell..
        /// </summary>
        public static string ReadCell_Result_Description {
            get {
                return ResourceManager.GetString("ReadCell_Result_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string ReadCell_Result_DisplayName {
            get {
                return ResourceManager.GetString("ReadCell_Result_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sheet containing the cell that will be read from..
        /// </summary>
        public static string ReadCell_SheetName_Description {
            get {
                return ResourceManager.GetString("ReadCell_SheetName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet Name.
        /// </summary>
        public static string ReadCell_SheetName_DisplayName {
            get {
                return ResourceManager.GetString("ReadCell_SheetName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reads a column of cells from a worksheet and returns the values as an array..
        /// </summary>
        public static string ReadColumn_Description {
            get {
                return ResourceManager.GetString("ReadColumn_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Column.
        /// </summary>
        public static string ReadColumn_DisplayName {
            get {
                return ResourceManager.GetString("ReadColumn_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of cells to read from the column. If left blank, or set to zero or less, all cells are read..
        /// </summary>
        public static string ReadColumn_Limit_Description {
            get {
                return ResourceManager.GetString("ReadColumn_Limit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Cells.
        /// </summary>
        public static string ReadColumn_Limit_DisplayName {
            get {
                return ResourceManager.GetString("ReadColumn_Limit_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array of values read from the column..
        /// </summary>
        public static string ReadColumn_Result_Description {
            get {
                return ResourceManager.GetString("ReadColumn_Result_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string ReadColumn_Result_DisplayName {
            get {
                return ResourceManager.GetString("ReadColumn_Result_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the worksheet to read from..
        /// </summary>
        public static string ReadColumn_SheetName_Description {
            get {
                return ResourceManager.GetString("ReadColumn_SheetName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet Name.
        /// </summary>
        public static string ReadColumn_SheetName_DisplayName {
            get {
                return ResourceManager.GetString("ReadColumn_SheetName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell address (in range format, e.g.: A1) that defines the column to start reading..
        /// </summary>
        public static string ReadColumn_StartingCell_Description {
            get {
                return ResourceManager.GetString("ReadColumn_StartingCell_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Cell.
        /// </summary>
        public static string ReadColumn_StartingCell_DisplayName {
            get {
                return ResourceManager.GetString("ReadColumn_StartingCell_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reads the value of a range from a spreadsheet as a DataTable. If the range is not specified, all used cells in the spreadsheet are read. If the range is specified as a cell, all used rows starting from that cell is read..
        /// </summary>
        public static string ReadRange_Description {
            get {
                return ResourceManager.GetString("ReadRange_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Range.
        /// </summary>
        public static string ReadRange_DisplayName {
            get {
                return ResourceManager.GetString("ReadRange_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies if the first row in the range should be considered column headers definitions. If set to false, the columns in the DataTable will use the following pattern &quot;Col{number}&quot;, e.g.: Col1, Col2, Col3, etc..
        /// </summary>
        public static string ReadRange_HasHeaders_Description {
            get {
                return ResourceManager.GetString("ReadRange_HasHeaders_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Headers.
        /// </summary>
        public static string ReadRange_HasHeaders_DisplayName {
            get {
                return ResourceManager.GetString("ReadRange_HasHeaders_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines the number of rows that composes the header. The values of these rows are concatenated..
        /// </summary>
        public static string ReadRange_HeaderRows_Description {
            get {
                return ResourceManager.GetString("ReadRange_HeaderRows_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headers Rows.
        /// </summary>
        public static string ReadRange_HeaderRows_DisplayName {
            get {
                return ResourceManager.GetString("ReadRange_HeaderRows_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the range of cells to be read. If this value is not specified, all used cells of the spreadsheet is read. If the value consists of only one cell, all used rows in the spreadsheet are read starting from that cell. (Default: A1).
        /// </summary>
        public static string ReadRange_Range_Description {
            get {
                return ResourceManager.GetString("ReadRange_Range_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        public static string ReadRange_Range_DisplayName {
            get {
                return ResourceManager.GetString("ReadRange_Range_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output DataTable in which the read data is stored..
        /// </summary>
        public static string ReadRange_Result_Description {
            get {
                return ResourceManager.GetString("ReadRange_Result_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Table.
        /// </summary>
        public static string ReadRange_Result_DisplayName {
            get {
                return ResourceManager.GetString("ReadRange_Result_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines the number of rows that composes a single record. The row values are concatenated..
        /// </summary>
        public static string ReadRange_RowsPerRecord_Description {
            get {
                return ResourceManager.GetString("ReadRange_RowsPerRecord_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows Per Record.
        /// </summary>
        public static string ReadRange_RowsPerRecord_DisplayName {
            get {
                return ResourceManager.GetString("ReadRange_RowsPerRecord_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the sheet from the workbook..
        /// </summary>
        public static string ReadRange_SheetName_Description {
            get {
                return ResourceManager.GetString("ReadRange_SheetName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet Name.
        /// </summary>
        public static string ReadRange_SheetName_DisplayName {
            get {
                return ResourceManager.GetString("ReadRange_SheetName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reads a row of cells from a worksheet and returns the values as an array..
        /// </summary>
        public static string ReadRow_Description {
            get {
                return ResourceManager.GetString("ReadRow_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Row.
        /// </summary>
        public static string ReadRow_DisplayName {
            get {
                return ResourceManager.GetString("ReadRow_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of cells to read from the row. If left blank, or set to zero or less, all cells are read..
        /// </summary>
        public static string ReadRow_Limit_Description {
            get {
                return ResourceManager.GetString("ReadRow_Limit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Cells.
        /// </summary>
        public static string ReadRow_Limit_DisplayName {
            get {
                return ResourceManager.GetString("ReadRow_Limit_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array of values read from the row..
        /// </summary>
        public static string ReadRow_Result_Description {
            get {
                return ResourceManager.GetString("ReadRow_Result_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string ReadRow_Result_DisplayName {
            get {
                return ResourceManager.GetString("ReadRow_Result_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the worksheet to read from..
        /// </summary>
        public static string ReadRow_SheetName_Description {
            get {
                return ResourceManager.GetString("ReadRow_SheetName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet Name.
        /// </summary>
        public static string ReadRow_SheetName_DisplayName {
            get {
                return ResourceManager.GetString("ReadRow_SheetName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell address (in range format, e.g.: A1) that defines the row to start reading..
        /// </summary>
        public static string ReadRow_StartingCell_Description {
            get {
                return ResourceManager.GetString("ReadRow_StartingCell_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Cell.
        /// </summary>
        public static string ReadRow_StartingCell_DisplayName {
            get {
                return ResourceManager.GetString("ReadRow_StartingCell_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renames an existing worksheet in the workbook. Use this activity when you need to change the name of a specific sheet..
        /// </summary>
        public static string RenameSheet_Description {
            get {
                return ResourceManager.GetString("RenameSheet_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Sheet.
        /// </summary>
        public static string RenameSheet_DisplayName {
            get {
                return ResourceManager.GetString("RenameSheet_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New name for the worksheet. This property is required and must be unique within the workbook..
        /// </summary>
        public static string RenameSheet_NewSheetName_Description {
            get {
                return ResourceManager.GetString("RenameSheet_NewSheetName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Sheet Name.
        /// </summary>
        public static string RenameSheet_NewSheetName_DisplayName {
            get {
                return ResourceManager.GetString("RenameSheet_NewSheetName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current name of the worksheet to be renamed. This property is required and the sheet must exist in the workbook..
        /// </summary>
        public static string RenameSheet_SheetName_Description {
            get {
                return ResourceManager.GetString("RenameSheet_SheetName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet Name.
        /// </summary>
        public static string RenameSheet_SheetName_DisplayName {
            get {
                return ResourceManager.GetString("RenameSheet_SheetName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immediately saves all changes made to the workbook to disk, instead of waiting for the Use Workbook container to save them at the end. Use this activity when the workbook needs to be persisted early for operations outside of the current read/write workflow..
        /// </summary>
        public static string SaveWorkbook_Description {
            get {
                return ResourceManager.GetString("SaveWorkbook_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Workbook.
        /// </summary>
        public static string SaveWorkbook_DisplayName {
            get {
                return ResourceManager.GetString("SaveWorkbook_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens a workbook and share its instance across the child activities..
        /// </summary>
        public static string WorkbookScope_Description {
            get {
                return ResourceManager.GetString("WorkbookScope_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Workbook.
        /// </summary>
        public static string WorkbookScope_DisplayName {
            get {
                return ResourceManager.GetString("WorkbookScope_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password required for open the workbook if it is password-protected..
        /// </summary>
        public static string WorkbookScope_Password_Description {
            get {
                return ResourceManager.GetString("WorkbookScope_Password_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string WorkbookScope_Password_DisplayName {
            get {
                return ResourceManager.GetString("WorkbookScope_Password_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the list of sheet names contained in the workbook..
        /// </summary>
        public static string WorkbookScope_SheetNames_Description {
            get {
                return ResourceManager.GetString("WorkbookScope_SheetNames_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet Names.
        /// </summary>
        public static string WorkbookScope_SheetNames_DisplayName {
            get {
                return ResourceManager.GetString("WorkbookScope_SheetNames_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to the workbook..
        /// </summary>
        public static string WorkbookScope_WorkbookPath_Description {
            get {
                return ResourceManager.GetString("WorkbookScope_WorkbookPath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workbook Path.
        /// </summary>
        public static string WorkbookScope_WorkbookPath_DisplayName {
            get {
                return ResourceManager.GetString("WorkbookScope_WorkbookPath_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the workbook path.
        /// </summary>
        public static string WorkbookScope_WorkbookPath_Placeholder {
            get {
                return ResourceManager.GetString("WorkbookScope_WorkbookPath_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address of the target cell (e.g., A1, B5) where the value will be written..
        /// </summary>
        public static string WriteCell_CellAddress_Description {
            get {
                return ResourceManager.GetString("WriteCell_CellAddress_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Address.
        /// </summary>
        public static string WriteCell_CellAddress_DisplayName {
            get {
                return ResourceManager.GetString("WriteCell_CellAddress_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writes a single value into a specific cell of an Excel worksheet. If the target sheet does not exist, a new one is created. Any existing value in the specified cell is overwritten..
        /// </summary>
        public static string WriteCell_Description {
            get {
                return ResourceManager.GetString("WriteCell_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Cell.
        /// </summary>
        public static string WriteCell_DisplayName {
            get {
                return ResourceManager.GetString("WriteCell_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the worksheet to write the cell value into. A new sheet is created if it does not exist..
        /// </summary>
        public static string WriteCell_SheetName_Description {
            get {
                return ResourceManager.GetString("WriteCell_SheetName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet Name.
        /// </summary>
        public static string WriteCell_SheetName_DisplayName {
            get {
                return ResourceManager.GetString("WriteCell_SheetName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content to be written into the specified cell. Any existing value in the cell is replaced..
        /// </summary>
        public static string WriteCell_Value_Description {
            get {
                return ResourceManager.GetString("WriteCell_Value_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string WriteCell_Value_DisplayName {
            get {
                return ResourceManager.GetString("WriteCell_Value_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates if column names are written as headers..
        /// </summary>
        public static string WriteRange_AddHeaders_Description {
            get {
                return ResourceManager.GetString("WriteRange_AddHeaders_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Headers.
        /// </summary>
        public static string WriteRange_AddHeaders_DisplayName {
            get {
                return ResourceManager.GetString("WriteRange_AddHeaders_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source DataTable to write into the worksheet..
        /// </summary>
        public static string WriteRange_DataTable_Description {
            get {
                return ResourceManager.GetString("WriteRange_DataTable_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Table.
        /// </summary>
        public static string WriteRange_DataTable_DisplayName {
            get {
                return ResourceManager.GetString("WriteRange_DataTable_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writes a DataTable into an Excel worksheet starting at a specified cell (default A1). If the target sheet does not exist, a new one is created. All existing values in the target range are overwritten..
        /// </summary>
        public static string WriteRange_Description {
            get {
                return ResourceManager.GetString("WriteRange_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Range.
        /// </summary>
        public static string WriteRange_DisplayName {
            get {
                return ResourceManager.GetString("WriteRange_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the worksheet to write data into..
        /// </summary>
        public static string WriteRange_SheetName_Description {
            get {
                return ResourceManager.GetString("WriteRange_SheetName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet Name.
        /// </summary>
        public static string WriteRange_SheetName_DisplayName {
            get {
                return ResourceManager.GetString("WriteRange_SheetName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top-left cell where writing begins..
        /// </summary>
        public static string WriteRange_StartingCell_Description {
            get {
                return ResourceManager.GetString("WriteRange_StartingCell_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Cell.
        /// </summary>
        public static string WriteRange_StartingCell_DisplayName {
            get {
                return ResourceManager.GetString("WriteRange_StartingCell_DisplayName", resourceCulture);
            }
        }
    }
}
